### ISSUE TITLE
About JSON instances…

### ISSUE THREAD

**Issue by dustin** [NorfairKing/syds-rules-for-sustainable-haskell#2]
I disagree with the idea of writing out JSON instances for a couple of reasons:

1. It's tedious and repetitive.
2. I don't want to write or have to read code a computer can without a good reason.

As far as I can tell, it's not the actual hand-written JSON instances that are important, but stability of the encoding and decoding.  Using generics consistently will keep round-tripping happy, but not offer any consistency guarantees.  In addition to round trip testing (which is critical), golden testing offers stability guarantees beyond what one might get from the manual instances.

e.g., if your object includes another object and that included object changes, you may be aware of the local impact, but not be aware of downstream impact.  The downstream user may not be aware of your change, but may be affected by that.  Golden tests provide exemplars humans can look at with stability guarantees (even transitively!) that the same input continues to serialize to the same result.  When anything changes, it's immediately obvious.

**Comment by dustin** [comment]
Perhaps a good general statement here is "write test to detect when serialization changes."

I generally don't like the idea of "change detector" tests, but that's because it's a thing people do accidentally because they don't know how to write a good test.  Sometimes, it is what you actually want.

**Comment by emberdart** [comment]
Synchronisation is a big issue with manual instances, I'd agree.

**Comment by joelmccracken** [comment]
I asked Syd about justifying these rules on twitter; its hard to suggest
alternatives without understanding the motivating factors.

For example, if the reason for doing it manually is to avoid weird issues
with domain data coupling, then it might make sense to suggest having
separate json types and domain types, and functions that convert between
them.

**Comment by joelmccracken** [comment]
Very cool, makes sense, thanks
